version: '3.8'

services:
  backend-redis-playground-master:
    image: bitnami/redis:latest
    container_name: backend-redis-playground-master
    hostname: backend-redis-playground-master
    environment:
      - 'REDIS_REPLICATION_MODE=master'
      - 'ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '6380:6380'
  backend-redis-playground-replicas-1:
    image: bitnami/redis:latest
    container_name: backend-redis-playground-replicas-1
    hostname: backend-redis-playground-replicas-1
    environment:
      - 'REDIS_REPLICATION_MODE=slave'
      - 'REDIS_MASTER_HOST=backend-redis-playground-master'
      - 'ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '6381:6380'
    depends_on:
      - 'backend-redis-playground-master'
