version: '3.8'

services:
  backend-redis-playground:
    image: redis:latest
    container_name: backend-redis-playground
    ports:
      - '6379:6379'
    volumes:
      - './redis.conf:/redis.conf'
    command: redis-server /redis.conf --port 6379
    restart: always
