version: '3.8'

services:
  backend-redis-playground:
    image: redis:latest
    container_name: backend-redis-playground
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    restart: always
