spring:
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
